- hosts: local

  tasks:
    - name: Crear directorio de ejemplo
      file:
        path: /home/isard/gitops_demo
        state: directory
        mode: '0755'

    - name: Crear archivo gestionado por GitOps
      copy:
        dest: /home/isard/gitops_demo/info.txt
        content: "Configurado automaticamente desde GitOps\n"
    
    - name: Crear estructura de proyecto
      file:
        path: /home/isard/gitops_demo/app/logs
        state: directory

    - name: Crear usuario alumno
      user:
        name: alumno
        state: present