- hosts: local
  
  tasks:
    - name: Crear directorio de ejemplo
      file:
        path: /home/isard/gitops_demo
        state: directory
        mode: '0755'

    - name: Crear archivo gestionado por GitOps
      copy:
        dest: /home/isard/gitops_demo/info.txt
        content: "Modificacion Configuracion desde GitOps\n"
    