name: GitOps Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      
      - name: Comprobar sudo en el runner
        run: |
          whoami
          id
          sudo -n whoami
      
      - name: Ejecutar Ansible
        run: ansible-playbook -i inventario.ini playbook.yml